### ISSUE TITLE
add escapeHtml() and translate()

### ISSUE THREAD

**Issue by antiphp** [fabiopaiva/zf2-navigation-bootstrap3#2]
Hi,

thank you for your effort. I miss two points: escaping and translating

<?php echo $this->escapeHtml($this->translate($child->getLabel())); ?>

Best,
antiphp

**Comment by berturion** [comment]
I totally agree. Translation is really missing.

**Comment by berturion** [comment]
Thanks !

I don't know why, the textDomain is lost when using the partial.

I call the menu in my layout like this:

    <div class="collapse navbar-collapse" id="zf2-navigation-bootstrap3-1">
        <?php
            echo $this->navigation('navigation')
                    ->setTranslatorTextDomain('MyTextDomain')
                    ->menu()
                    ->setUlClass('nav navbar-nav')
                    ->setPartial('partial/zf2-navigation-bootstrap3/navigation.phtml');
        ?>
    </div>

Then, in the partial, the textDomain is `default`. So I must add this:

    $nav = $this->navigation();
    $trans = $nav->getTranslator();
    $textDomain = $nav->getTranslatorTextDomain();

...and call the translator like this:

    $trans->translate($page->getLabel(), $textDomain)

I tried to use the `translate` method from `$nav` but I get this error:

    Fatal error: Zend\Navigation\Exception\BadMethodCallException: Bad method call: Unknown method Zend\Navigation\Navigation::translate

Maybe I do something wrong, I think it is stange. Any help please ?

**Comment by fabio-paiva-sp** [comment]
@berturion, this feature is present now. Just use: 

```
<div class="collapse navbar-collapse" id="zf2-navigation-bootstrap3-1">
    <?php
        echo $this->navigation('navigation')
                ->setTranslatorTextDomain('MyTextDomain')
                ->menu()
                ->setUlClass('nav navbar-nav')
                ->setPartial('partial/zf2-navigation-bootstrap3/navigation.phtml');
    ?>
</div>
```
