### ISSUE TITLE
Can put acl?

### ISSUE THREAD

**Issue by IgorDePaula** [fabiopaiva/zf2-navigation-bootstrap3#3]
Can put acl?

**Comment by fabio-paiva-sp** [comment]
Add your acl to default Navigation on Module::onBootstrap method:

```
    if (!Console::isConsole()) {    
        $sm = $e->getApplication()->getServiceManager();
        // Add ACL information to the Navigation view helper
        $authorize = $sm->get('BjyAuthorizeServiceAuthorize');
        $acl = $authorize->getAcl();
        $role = $authorize->getIdentity();
        \Zend\View\Helper\Navigation::setDefaultAcl($acl);
        \Zend\View\Helper\Navigation::setDefaultRole($role);
    }
```

**Comment by IgorDePaula** [comment]
Unfortunately I don't use bjyauthorize, it is very complicated and Zend Framework has simple mechanisms for do this. In first versions of zend framework I could  do, now I cant do again.

**Comment by fabio-paiva-sp** [comment]
You can use the Zend default Acl.

```
    \Zend\View\Helper\Navigation::setDefaultAcl($acl);
    \Zend\View\Helper\Navigation::setDefaultRole($role);
```

eg 
https://zf2.readthedocs.org/en/release-2.3.0/modules/zend.navigation.view.helpers.html

**Comment by IgorDePaula** [comment]
I used,but dont work.

2015-03-17 12:11 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
Dois brasileiros conversando em inglês.... hehe

Cara, se você usar o navigation do zend (sem partial), o acl deve funcionar, caso contrário o problema deve ser o jeito que configurou o ACL. 
Eu gosto de usar o BjyAuthorize por que ele é fácil de configurar a rota como resource, daí o navigation bloqueia.
Se quiser depurar, o acl do navigation fica neste arquivo

https://github.com/zendframework/zf2/blob/master/library/Zend/View/Helper/Navigation/Listener/AclListener.php

**Comment by IgorDePaula** [comment]
Pois eh, eu fui conversar com outro brasileiro outro dia e ele deu um fora
so querendo conversar em ingles. O bjyauthorize eh bem completo,mas
complexo, eu o conheco desde o tempo q ele nasceu, mas ate hoje nao entendi
sua lugica, e nem o autor kiz explicar,outro que me deu um fora. Entao, ha
1 ano e meio eu fiz um projeto usando partial mesmo e o acl funcionou,
tentei reproduzir adaptar mas algo mudou e nao estou descobrindo o q eh...

Em 17 de março de 2015 13:46, Fábio Felipe Paiva notifications@github.com
escreveu:

**Comment by fabio-paiva-sp** [comment]
Eu gosto muito do BjyAuthorize. Vai ser a próxima postagem do meu blog.
Sobre conversar em inglês, quando vai ser útil pra toda comunidade tudo bem, mas quando vira um caso específico não tem porque.

**Comment by IgorDePaula** [comment]
Consegui por o acl...agora so os submenus que nao estao sendo renderizados corretamente

**Comment by fabio-paiva-sp** [comment]
Algum erro?

**Comment by IgorDePaula** [comment]
Sim, meu, eu tinha que colocar no final o metodo renderMenu, agora estou ajustando os submenus.

**Comment by IgorDePaula** [comment]
os submenus eles esta renderizando o ul sem a classe dropdown-menu e o li pai sem a classe dropdown-toggle

**Comment by fabio-paiva-sp** [comment]
Abre um novo issue e descreva o problema.

Atenciosamente,
Fábio Paiva

2015-03-18 11:27 GMT-03:00 Igor C. de Paula notifications@github.com:
