### ISSUE TITLE
Submenus sem classes

### ISSUE THREAD

**Issue by IgorDePaula** [fabiopaiva/zf2-navigation-bootstrap3#4]
Quando aplicado ao acl os submenus ficam sem classes 
![navigation](https://cloud.githubusercontent.com/assets/2833993/6711006/2e7364a6-cd63-11e4-8441-79a26a5ef178.png)

**Comment by fabio-paiva-sp** [comment]
Igor, tem certeza que setou o partial?
Pergunto por que a tag ul tem a classe setada no código, seria impossível ela vir sem a classe
https://github.com/fabiopaiva/zf2-navigation-bootstrap3/blob/master/navigation.phtml#L44

poste como ficou a chamada do view helper no layout

**Comment by IgorDePaula** [comment]
Meu layout esta assim

https://gist.github.com/IgorDePaula/5734cf95c88df96f50b3

2015-03-18 12:13 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
Confere seu partial, se o arquivo existe

```
   ->setPartial('partials/navigation')
```

Padrão:

```
    ->setPartial('partial/zf2-navigation-bootstrap3/navigation.phtml')
```

**Comment by IgorDePaula** [comment]
Sim, existe,fiz a modificacao e o erro persiste. Se ele nao estivesse encontrando o partial ele reclamaria, entretanto nao reclamou. Tambem acho impossivel disso acontecer.

Meu acl esta assim
https://gist.github.com/IgorDePaula/39a65ed05a40743374d5

Meu controller plugin para as permissoes e acl estao assim
https://gist.github.com/IgorDePaula/d6203d3f81ce947a6e46

**Comment by fabio-paiva-sp** [comment]
Remove o partial e verifica se continua da mesma forma.
Certeza que é o partial que não está carregando o arquivo correto.

**Comment by IgorDePaula** [comment]
Removi, deu o mesmo problema, entretanto se eu nao colocar o metodo
renderMenu(), ele nao aplica o acl.

Em 18 de março de 2015 14:28, Fábio Felipe Paiva notifications@github.com
escreveu:

**Comment by fabio-paiva-sp** [comment]
Isso significa que ele está carregando o layout padrão, não está aplicando o partial.

**Comment by IgorDePaula** [comment]
ele deve estar carregando o layout padrao por conta do renderMenu, mas semo
renderMenu ele nao aplica o acl.

2015-03-18 14:36 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
Tenta assim:

```
   <?php echo $this->
        navigation('navigation')
        ->menu()
        ->setUlClass('nav navbar-nav')
        ->setPartial('partial/zf2-navigation-bootstrap3/navigation.phtml'); 
    ?>
```

**Comment by IgorDePaula** [comment]
apareceu formatado direitinho, eu entendi o que voce quiz dizer...mas eu
preciso de aplicar o acl... =(

2015-03-18 14:46 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
o ACL é aplicado no onBootstrap, não entendi por que não deu certo.

**Comment by IgorDePaula** [comment]
Eu nao estou aplicando o acl no on bootstrap do module, e sim aplicando um
plugin no controller antes dele ser instanciado.

2015-03-18 14:59 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
Como?

**Comment by IgorDePaula** [comment]
Meu onbootstrap esta assim

https://gist.github.com/IgorDePaula/18bb7871cbfba7104930

e o plugin  seria este

https://gist.github.com/IgorDePaula/d6203d3f81ce947a6e46

2015-03-18 15:07 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
Configura isto

```
     \Zend\View\Helper\Navigation::setDefaultAcl($acl);
     \Zend\View\Helper\Navigation::setDefaultRole($role);
```

**Comment by IgorDePaula** [comment]
agora foi, estranho que antes eu ja havia testado esta opcao....

Muuuuitiiiisssimo obrigado pela atencao e paciencia.

2015-03-18 15:31 GMT-03:00 Fábio Felipe Paiva notifications@github.com:

**Comment by fabio-paiva-sp** [comment]
Tranquilo
